// constantes para os tokens 
enum Tag { ID = 256, INTEGER, FLOATING, STRING, TYPE, TRUE, FALSE, MAIN, IF, THEN, ELSE, NUM, 
            WHILE, DO, OR, AND, EQ, ATT, NEQ, LTE, GTE, LT, LE, NE, GT,
            BOOLEAN,  CHAVEESQ, CHAVEDIR, PARENESQ, PARENDIR, COLCHETEESQ, COLCHETEDIR, PONTOVIRGULA,
            SOMA, SUBT, MULT, DIV, NEGACAO};
